### ISSUE TITLE
How to add a rasterization pass to build a hybrid framework?

### ISSUE THREAD

**Issue by AntonyChan818** [philcn/DXRExperiments#4]
// Insert rasterizeration code here

		// Run denoiser with mock input textures
		if (mBypassRaytracing && mDenoiser->mActive) 
		{
			mDenoiser->dispatch(commandList, DenoiseCompositor::InputComponents{ 0 }, currentFrame, GetWidth(), GetHeight());
			BlitToBackbuffer(mDenoiser->getOutputResource());
		}

Is it right that I have to write a separate Rasterization Pipeline and new Model/Scene class if I want a rasterizeration result for the first hit?

**Comment by philcn** [comment]
You're right, this project only aimed at building an abstraction layer over the DXR API and nothing else.

**Comment by AntonyChan818** [comment]
OK, thank you.
It seems a little bit complicate to integrate rasterization and DXR using same context.
